# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/ironarachne/towngen
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          cd cmd/towngend
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t ironarachne/towngend:$TAG -t ironarachne/towngend:latest .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push ironarachne/towngend:$TAG
          docker push ironarachne/towngend:latest
  deploy:
    machine:
        enabled: true
    steps:
      - run: curl -X POST 'https://portainer.ironarachne.com/api/webhooks/f0620057-6ee0-4bc7-86b7-ff7dfb14eb86'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
